name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: _work/devpipelinetest/devpipelinetest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.208.169.188 >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          ssh ec2-user@18.208.169.188 << 'EOF'
            cd /home/ec2-user/app/_work/devpipelinetest/devpipelinetest/backend
            git pull origin main
            docker-compose up --build -d
          EOF

